<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="164.723" tests="3" failures="3">
  <testsuite name="Root Suite" timestamp="2023-05-16T09:24:50" tests="3" file="cypress\e2e\WebSoft\Learning_testing_management\Testing_management\Portal_test_completion_succesfully.cy.js" time="164.704" failures="3">
    <testcase name="Прохождение теста успешно" time="0.000" classname="Прохождение теста успешно">
      <failure message="Timed out retrying after 40000ms: expected &apos;https://dev.websoft.ru:16598/qtiplayer3/presentation.htm?aicc_sid=7233708944228177364&amp;aicc_url=%2Fhandler%2Ehtml&amp;width=1018&amp;height=682&amp;fit=1&amp;lang=ru&amp;send=q&amp;display=item&amp;rubric=ass&amp;map=1&amp;navmap=1&amp;navstrict=0&amp;navprog=1&amp;timing=1&amp;nextbind=1&amp;reslock=0&amp;break=0&amp;displayresscore=1&amp;feedback=1&amp;failed=1&amp;displaymax=1&amp;path=/webtutor/00044/1/#loaded&apos; to include &apos;/tests/&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 40000ms: expected 'https://dev.websoft.ru:16598/qtiplayer3/presentation.htm?aicc_sid=7233708944228177364&aicc_url=%2Fhandler%2Ehtml&width=1018&height=682&fit=1&lang=ru&send=q&display=item&rubric=ass&map=1&navmap=1&navstrict=0&navprog=1&timing=1&nextbind=1&reslock=0&break=0&displayresscore=1&feedback=1&failed=1&displaymax=1&path=/webtutor/00044/1/#loaded' to include '/tests/'
    at TestingManagementCommands.openTestPlayer (webpack:///./cypress/e2e/Page_object/Page_testing_management.cy.js:35:9)
    at Context.eval (webpack:///./cypress/e2e/WebSoft/Learning_testing_management/Testing_management/Portal_test_completion_succesfully.cy.js:43:30)]]></failure>
    </testcase>
    <testcase name="Проверка статуса" time="0.000" classname="Проверка статуса">
      <failure message="Timed out retrying after 40000ms: expected &apos;&lt;div#WT_0x637B77422CF629BF.wt-lp-witemlist-workarea.wt-lp-witemlist-type-row.wt-lp-base-font-size.wt-lp-workarea-width&gt;&apos; to contain &apos;Пройден&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 40000ms: expected '<div#WT_0x637B77422CF629BF.wt-lp-witemlist-workarea.wt-lp-witemlist-type-row.wt-lp-base-font-size.wt-lp-workarea-width>' to contain 'Пройден'
    at MainCommands.findHeader (webpack:///./cypress/e2e/Page_object/All_pages_commands.cy.js:15:7)
    at Context.eval (webpack:///./cypress/e2e/WebSoft/Learning_testing_management/Testing_management/Portal_test_completion_succesfully.cy.js:49:17)]]></failure>
    </testcase>
    <testcase name="Проверка баллов" time="0.000" classname="Проверка баллов">
      <failure message="Timed out retrying after 40000ms: expected &apos;&lt;div#WT_0x637B774B60D76ABE.wt-lp-witemlist-workarea.wt-lp-witemlist-type-row.wt-lp-base-font-size.wt-lp-workarea-width&gt;&apos; to contain &apos;6&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 40000ms: expected '<div#WT_0x637B774B60D76ABE.wt-lp-witemlist-workarea.wt-lp-witemlist-type-row.wt-lp-base-font-size.wt-lp-workarea-width>' to contain '6'
    at MainCommands.findHeader (webpack:///./cypress/e2e/Page_object/All_pages_commands.cy.js:15:7)
    at Context.eval (webpack:///./cypress/e2e/WebSoft/Learning_testing_management/Testing_management/Portal_test_completion_succesfully.cy.js:54:17)]]></failure>
    </testcase>
  </testsuite>
</testsuites>